# Generated by Django 3.0.5 on 2022-07-18 20:58

from django.db import migrations, models
import django.db.models.deletion
import perpustakaan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buku',
            fields=[
                ('idbuku', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('npm', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('jurusan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='pinjam',
            fields=[
                ('idpinjam', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('kembali', models.DateField(default=perpustakaan.models.balik)),
                ('idbuku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('npm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.mahasiswa')),
            ],
        ),
    ]
