# Generated by Django 3.0.5 on 2022-07-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='kategori',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
