# Generated by Django 3.0.5 on 2022-07-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_auto_20220723_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='idpinjam',
            field=models.AutoField(default=201001, primary_key=True, serialize=False),
        ),
    ]
