# Generated by Django 3.0.5 on 2022-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_auto_20220723_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='idpinjam',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
