# Generated by Django 3.0.5 on 2022-07-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0005_auto_20220723_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='penerbit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='sinopsis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='tahunterbit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
